global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'kafka'
    static_configs:
      - targets: ['localhost:7071']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter1:9100']

  - job_name: 'cadvisor1'
    static_configs:
      - targets: ['cadvisor1:8080']